services:
  shangtang-register:
    build: .
    container_name: shangtang-register
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    networks:
      - newapi_web

networks:
  newapi_web:
    external: true
    name: newapi_web
